# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
        config.vm.box = "ubuntu/trusty64"
        config.vm.box_check_update = false
  config.vm.define "chefsrv" do |dev|
        dev.vm.network  "private_network", ip: "192.168.1.20"
        dev.vm.hostname = "chefsrv"
        config.vm.synced_folder "~/workspace/practice/vagrant/chefsrv", "/samba/sync/", type:"virtualbox"
        dev.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
      end
  end
  config.vm.define "chefcli" do |dev|
        dev.vm.network  "private_network", ip: "192.168.1.30"
        dev.vm.hostname = "chefcli"
        config.vm.synced_folder "~/workspace/practice/vagrant/chefcli", "/samba/sync/", type:"virtualbox"
        dev.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
  end
end
