Vagrant.configure("2") do |config|
        config.vm.box = "ubuntu/trusty64"
        config.vm.hostname = "chef-server"
	config.vm.box_check_update = false
	config.vm.synced_folder "~/workspace/practice/vagrant/chefsrv", "/samba/sync/", type:"virtualbox"
	config.vm.network  "private_network", ip: "192.168.1.10"
        config.vm.provider "virtualbox" do |vb|
        	vb.memory = "2048"
      end
	config.vm.provision 'shell', inline: <<-SHELL
		cd ~
		wget -q https://packages.chef.io/files/stable/chef-server/12.17.33/ubuntu/16.04/chef-server-core_12.17.33-1_amd64.deb
		sudo dpkg -i chef-server-core*
		sudo chef-server-ctl reconfigure
		sudo chef-server-ctl user-create chefroot Mr Chef  mrchef@polnayzopa.io 'asd123' --filename /tmp/mrchef.pem
		sudo chef-server-ctl org-create hsh 'HomeSweetHome' --association_user chefroot --filename /tmp/hsh.pem
		sudo chef-server-ctl install chef-manage
		sudo chef-server-ctl reconfigure
		sudo chef-manage-ctl reconfigure
	SHELL
end
